export type GrandFamily =
  | 'survival'
  | 'course'
  | 'target'
  | 'collect'
  | 'puzzle'
  | 'sport'
  | 'tactics';
export type GrandPolicy = 'survival' | 'race' | 'points' | 'accuracy';
function game<I extends string>(
  id: I,
  name: string,
  family: GrandFamily,
  duration: number,
  world: string,
  brief: string,
  controls: string,
  action: string,
  policy: GrandPolicy = 'points',
  teams = false,
  heats = false,
) {
  return {
    id,
    name,
    family,
    duration,
    world,
    brief,
    controls,
    action,
    policy,
    teams,
    heats,
    category: heats
      ? 'Rotating 1 vs 3'
      : teams
        ? '2 vs 2 ' + family
        : family[0].toUpperCase() + family.slice(1),
    accent: {
      survival: '#ffb46d',
      course: '#83ccec',
      target: '#e9a7bb',
      collect: '#e5cd68',
      puzzle: '#baa5ef',
      sport: '#92d5ab',
      tactics: '#e6af7a',
    }[family],
    tip: heats
      ? 'Every player takes the solo role once. Scores carry across all four heats.'
      : teams
        ? 'Your team shares its result. Cover a different lane or role from your partner.'
        : family === 'survival'
          ? 'Watch the next hazard before committing. A well-timed secondary action can save you.'
          : family === 'course'
            ? 'A clean route beats constant speed. Recover at a checkpoint and keep moving.'
            : family === 'puzzle'
              ? 'Use small, deliberate inputs. Read the marked target before committing your move.'
              : family === 'target'
                ? 'Lead moving targets and wait for a clear shot. Each hit is decided by contact.'
                : 'Plan your next pickup while moving. Your score follows the objects you actually collect.',
  };
}
export const GRAND_CATALOG = [
  game(
    'tidetiles',
    'Tide Tiles',
    'survival',
    45,
    'Mangrove beacon lagoon',
    'Watch the beacon and reach a matching island before the others sink. Jump the gaps and share space carefully.',
    'WASD move · Space jump · E stomp',
    'Jump',
    'survival',
  ),
  game(
    'cannoncay',
    'Cannonball Cay',
    'survival',
    45,
    'Pirate raft cove',
    'Cannonball shadows warn where blasts will land. Keep your balance as impacts push you across the raft.',
    'WASD move · Space jump · Hold E brace',
    'Jump',
    'survival',
  ),
  game(
    'prickleice',
    'Prickle on Ice',
    'survival',
    40,
    'Frozen urchin tidepool',
    'Slide between bouncing urchins. Small ones can be jumped; two hits knock you out. Brake before trouble.',
    'WASD accelerate · Space jump · E brake',
    'Jump',
    'survival',
  ),
  game(
    'crabtraffic',
    'Crab Traffic',
    'survival',
    45,
    'Crab migration pier',
    'Crab herds shove across the pier. Find gaps, jump small crabs, and keep away from the open edges.',
    'WASD move · Space jump · Hold E brace',
    'Jump',
    'survival',
  ),
  game(
    'crumbleclock',
    'Crumble Clock',
    'survival',
    40,
    'Cenote countdown ruins',
    'Each numbered block counts down. Standing on one drains it faster. Keep a route to the next safe block.',
    'WASD move · Space jump · E shove',
    'Jump',
    'survival',
  ),
  game(
    'lanternlurk',
    'Lantern Lurk',
    'survival',
    45,
    'Moonlit salamander temple',
    'A salamander follows your lantern, then breathes fire. Hide your light, use the pillars, and dodge its warning cone.',
    'WASD move · Space jump · Hold E shade lantern',
    'Jump',
    'survival',
  ),
  game(
    'vinevault',
    'Vine Vault',
    'course',
    45,
    'Giant-vine canopy',
    'Climb alternating leaves to the crown. Jump from a leaf and steer in the air; every fourth leaf is a checkpoint.',
    'A/D steer · Space jump · Hold E grip vine',
    'Jump',
    'race',
  ),
  game(
    'mangrovemotors',
    'Mangrove Motors',
    'course',
    50,
    'Winding mangrove rapids',
    'Thread your boat between logs. Each throttle tap commits to more speed; only two emergency brakes are available.',
    'A/D steer · Space raise throttle · E brake',
    'Throttle',
    'race',
  ),
  game(
    'bubbletrouble',
    'Bubble Trouble',
    'course',
    45,
    'Coral reef tunnel',
    'Swim along the reef course and avoid mines. Sprint costs energy; dive beneath mines and surface to recover.',
    'WASD swim · Hold Space sprint · Hold E dive',
    'Sprint',
    'race',
  ),
  game(
    'frostyfreight',
    'Frosty Freight',
    'course',
    55,
    'Banked glacier chute',
    'Share a sled: the front rider steers and pushes, while the rear rider leans and hops barriers. Both partners win together.',
    'A/D steer or lean · Space push or jump · E brake',
    'Push / hop',
    'race',
    true,
  ),
  game(
    'pelicanpilots',
    'Pelican Pilots',
    'course',
    55,
    'Sea-stack flight corridor',
    'Pilot through every hoop while your partner flaps to build lift. Watch altitude and wing heat to avoid a stall.',
    'WASD steer / trim · Hold Space boost / flap · E brake / vent',
    'Boost / flap',
    'race',
    true,
  ),
  game(
    'hotelhiccup',
    'Hotel Hiccup',
    'course',
    50,
    'Moonflower door hotel',
    'Find the working door on each floor. Wrong doors loop back; observe rivals and remember which doors you tried.',
    'WASD move · Space enter nearby door · E mark door',
    'Enter door',
    'race',
  ),
  game(
    'picklepatrol',
    'Pickle Patrol',
    'target',
    45,
    'Cracker-wall tank courtyard',
    'Fire ricocheting pickle bolts. Break cracker cover, lead your target, and retreat while your three-shot magazine reloads.',
    'WASD drive & aim · Space fire · Hold E lock position',
    'Fire',
    'survival',
  ),
  game(
    'mangosluggers',
    'Mango Sluggers',
    'target',
    35,
    'Sunset batting cages',
    'Read the pitch and swing as the mango reaches your bat. Clean contact launches it into higher-value distance rings.',
    'A/D stance · W/S loft · Space swing · E bunt',
    'Swing',
  ),
  game(
    'geckograffiti',
    'Gecko Graffiti',
    'target',
    45,
    'Toy-gecko paint pond',
    'Paint moving gecko boats in your team color. Lead shots across the pond; larger geckos need two hits.',
    'A/D along shore · W/S aim depth · Space fire · E bubble size',
    'Fire',
    'points',
    true,
  ),
  game(
    'skewergallery',
    'Skewer Gallery',
    'target',
    52,
    'Moving-cover carnival',
    'Take a turn as the skewer shooter, then dodge behind moving cover. Each player gets one twelve-second solo heat.',
    'WASD aim / dodge · Space fire / dash · Hold E focus / duck',
    'Fire / dash',
    'points',
    false,
    true,
  ),
  game(
    'boulderbuffet',
    'Boulder Buffet',
    'target',
    52,
    'Volcanic climbing slope',
    'Roll melons downhill as the solo chef. As a climber, dodge rocks and reach higher flags. Solo roles rotate each heat.',
    'WASD steer / climb · Hold-release Space roll / jump · E heavy rock / cling',
    'Roll / jump',
    'points',
    false,
    true,
  ),
  game(
    'returnsender',
    'Return to Sender',
    'target',
    45,
    'Six-belt parcel depot',
    'Run to belt switches and send cranky parcels into the rival depot. Your partner can cover the other lanes.',
    'WASD move · Space reverse nearby belt · E lock belt',
    'Reverse belt',
    'points',
    true,
  ),
  game(
    'sundaesummit',
    'Sundae Summit',
    'collect',
    40,
    'Floating sundae plaza',
    'Catch falling scoops beneath their shadows. Tall stacks wobble when you turn sharply; stabilize before moving again.',
    'WASD move · Space hop · Hold E stabilize',
    'Hop',
  ),
  game(
    'postcardpanic',
    'Postcard Panic',
    'collect',
    45,
    'Breezy beach post office',
    'Carry one envelope at a time to a moving mail cart. Colored express mail scores extra at its matching cart.',
    'WASD move · Space pick up / deliver · E drop',
    'Pick / deliver',
  ),
  game(
    'raingarden',
    'Rain Garden',
    'collect',
    45,
    'Glasshouse cloud garden',
    'Keep your planter under the wandering rain cloud. Open it to collect water and close it before a wind gust spills your work.',
    'WASD move · Hold Space collect rain · E shield',
    'Collect rain',
  ),
  game(
    'parasolpearls',
    'Parasol Pearls',
    'collect',
    40,
    'Pearl-filled cloud shaft',
    'Steer through pearl arcs while descending. Open your parasol to slow down; close it to dive past jellyfish.',
    'A/D steer · Hold Space open parasol · Hold E dive',
    'Open parasol',
  ),
  game(
    'coinquake',
    'Coinquake',
    'collect',
    40,
    'Lighthouse crane roof',
    'Collect coins, avoid falling metal coconuts, and bank your haul at a rim chute. A hit spills unbanked coins.',
    'WASD move · Space jump · Hold E at chute to bank',
    'Jump',
  ),
  game(
    'hooklinelunch',
    'Hook, Line & Lunch',
    'collect',
    45,
    'Three-lane fishing pier',
    'Aim and charge a cast toward moving snack rafts. Once hooked, reel carefully and let out slack when tension is high.',
    'A/D aim · Hold-release Space cast · W reel / S slack · E cancel',
    'Cast',
  ),
  game(
    'coconutcompass',
    'Coconut Compass',
    'puzzle',
    40,
    'Tilt-table coconut workshop',
    'Tilt your tabletop to uncover every square with the marble. Brake before edges and corners; a fall returns you to the center.',
    'WASD tilt · Hold Space brake · E nudge',
    'Brake',
    'race',
  ),
  game(
    'fossilfillet',
    'Fossil Fillet',
    'puzzle',
    35,
    'Fossil engraving quarry',
    'Guide your engraving tool around the fossil outline. Accurate coverage counts; extra cuts lower your score.',
    'WASD steer tool · Hold Space cut · E lift blade',
    'Cut',
    'accuracy',
  ),
  game(
    'lostluggage',
    'Lost Luggage',
    'puzzle',
    42,
    'Patterned baggage hall',
    'Study the nine-case rack, then carry each scattered case back to its remembered slot and orientation.',
    'WASD move · Space pick / place · E rotate case',
    'Pick / place',
    'accuracy',
  ),
  game(
    'doughdouble',
    'Dough Doppelganger',
    'puzzle',
    35,
    'Dumpling sculpture studio',
    'Match the target dough face by moving six handles. Grab a handle, pull it into place, then move to another.',
    'A/D select · Hold Space + WASD drag · E reset handle',
    'Grab handle',
    'accuracy',
  ),
  game(
    'bentoblocks',
    'Bento Blocks',
    'puzzle',
    50,
    'Stacking lunchbox factory',
    'Place falling ingredient pairs. Groups of three matching ingredients clear; falling blocks can trigger chain reactions.',
    'A/D move · Space rotate · S soft drop · E hard drop',
    'Rotate',
  ),
  game(
    'picnicpartition',
    'Picnic Partition',
    'puzzle',
    45,
    'Giant sandwich picnic',
    'Clear sandwich bites with your partner. Crust takes longer, and chewing spends stamina. Refill at the thermoses.',
    'WASD move · Hold Space eat · Hold E at thermos refill',
    'Eat',
    'points',
    true,
  ),
  game(
    'volleybuns',
    'Volley Buns',
    'sport',
    60,
    'Seaside volleyball court',
    'Get beneath the ball, then hit it over the net or set to your partner. Three contacts maximum before crossing the net.',
    'WASD move · Space jump & strike · E set',
    'Strike',
    'points',
    true,
  ),
  game(
    'puckpicnic',
    'Puck Picnic',
    'sport',
    60,
    'Lantern-lit hockey rink',
    'Chase the loose puck, control it near your stick, and charge a shot into the other goal. Your partner can defend.',
    'WASD skate · Hold-release Space shoot · E stick block',
    'Shoot',
    'points',
    true,
  ),
  game(
    'pineapplestrikers',
    'Pineapple Strikers',
    'sport',
    55,
    'Pineapple target stadium',
    'Kick the rolling shell into the five pineapples behind the rival line. Defend your remaining targets.',
    'WASD move · Space kick · E trap / tackle',
    'Kick',
    'points',
    true,
  ),
  game(
    'goalguava',
    'Goal Guava',
    'sport',
    52,
    'Guava goalkeeper arena',
    'Take turns defending the goal against three shooters. Saves score for the keeper; goals score for the shooter.',
    'A/D position · W/S aim · Hold-release Space shoot / jump · E dive / fake',
    'Shoot / jump',
    'points',
    false,
    true,
  ),
  game(
    'touchdowntiki',
    'Touchdown Tiki',
    'sport',
    52,
    'Three-arch tiki field',
    'As the solo runner, reach a scoring arch with three limited boosts. Defenders must time their tackles. Roles rotate.',
    'WASD move · Space boost / tackle · E feint / block',
    'Boost / tackle',
    'points',
    false,
    true,
  ),
  game(
    'paddleplunder',
    'Paddle Plunder',
    'sport',
    45,
    'Current-ring mangrove lake',
    'Each partner controls one paddle. Stroke together to go forward, split your strokes to turn, and collect pearl clusters.',
    'Hold Space paddle · Hold E reverse · A/D lean',
    'Paddle',
    'points',
    true,
  ),
  game(
    'crateescape',
    'Crate Escape',
    'tactics',
    52,
    'Tumbling crate warehouse',
    'The small crate escapes three larger crates. Each move commits to a tumble, so plan ahead. Everyone takes the small role.',
    'WASD tumble · Space dash / charge · E preview',
    'Dash / charge',
    'points',
    false,
    true,
  ),
  game(
    'rubblerunners',
    'Rubble Runners',
    'tactics',
    55,
    'Snack-cart canyon',
    'Clear the road so your team cart can move. Heavy hits crack armored boulders; quick punches finish smaller rocks.',
    'WASD move · Space punch · Hold-release E heavy hit',
    'Punch',
    'race',
    true,
  ),
] as const;
export type GrandKind = (typeof GRAND_CATALOG)[number]['id'];
export const GRAND_IDS: string[] = GRAND_CATALOG.map((g) => g.id);
export function grandInfo(kind: string) {
  return GRAND_CATALOG.find((g) => g.id === kind);
}
